server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # /api/entreprise/all  ->  http://backend:8080/entreprise/all
    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Routes Angular (/entreprises, /equipes...) : toujours servir index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
